name: Create Test Build - XCODE

on:
  workflow_dispatch: {}

#on: [push, pull_request]

jobs:
  buildForiOS:
    name: Build for iOS
    runs-on: ubuntu-latest
    #strategy:
    #  fail-fast: false
    #  matrix:
    #    targetPlatform:
    #      - iOS # Build an iOS player.
    #      - Android # Build an Android .apk standalone app.
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-iOS
          restore-keys: Library-

      - uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: iOS
          buildName: AutoBuild-${{ github.event.repository.name }}-iOS

      - uses: actions/upload-artifact@v2
        with:
          name: Autobuild-${{ github.event.repository.name }}-iOS
          path: build/iOS