name: Create Test Build - APK

on:
  workflow_dispatch: {}
  
  push:
    branches:
      - 'releases/test-release'

jobs:
  buildForAndroid:
    name: Create test build for Android
    runs-on: ubuntu-latest
    steps:
    
    #CHECKOUT
      - run: echo 'Checkout started'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
          
    #CACHE
      - run: echo 'Cache started'
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-Android
          restore-keys: Library-
         
    #BUILD
      - run: echo 'Build starting'
      - uses: game-ci/unity-builder@v2.0.4
        id: buildAndroid
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          #versioning: Semantic
          #androidTargetSdkVersion: AndroidApiLevel22
          targetPlatform: Android
          buildName: AutoBuild-${{ github.event.repository.name }}-Android
          androidAppBundle: false
          #androidKeystoreName: user.keystore
          #androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          #androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          #androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          #androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}

    #UPLOAD DIAWI 
      - run: echo 'Upload to diawi started'
      - uses: rnkdsh/action-upload-diawi@v1.2.5
        id: diawiUpload
        with:
            token: ${{ secrets.DIAWI_TOKEN }}
            file: build/Android/AutoBuild-${{ github.event.repository.name }}-Android.apk

    #SENDING
      - name: Send message to slack
        id: slackMessage
        uses: slackapi/slack-github-action@v1.19.0
        with:
            payload: |
                {
                  "build_url": "${{ steps.diawiUpload.outputs['url'] }}",
                  "build_info": "This is a test build, don't upload to store",
                  "game_name": "${{ github.event.repository.name }}"
                }
        env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}