name: iOS One-Time Setup

on: workflow_dispatch

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dir Check
        run: |
            echo -List Directory-
            ls -a
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '3.1'

      - name: Init bundles
        run: bundle install

      #- name: Build iOS
      #  shell: bash
      #  run: |
      #    bundle exec fastlane ios init_ci
      #  env:
      #    APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
      #    APP_STORE_CONNECT_KEY: ${{ secrets.APPSTORE_P8 }} # Raw .p8 value
      #    APP_STORE_CONNECT_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}

      #    GH_PAT: ${{ secrets.GH_PAT }}
      #    GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
      #    MATCH_REPOSITORY: ${{ secrets.MATCH_REPOSITORY }}



#jobs:
#  setup:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - run: |
#            echo -List Directory-
#            ls -a
#      - uses: ruby/setup-ruby@v1
#        with:
#          ruby-version: 2.7
#          #bundler-cache: true

#      - name: Build iOS
#        shell: bash
#        run: |
#          bundle exec fastlane init_ci
#        env:
#          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
#          APP_STORE_CONNECT_KEY: ${{ secrets.APPSTORE_P8 }} # Raw .p8 value
#          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}

#          GH_PAT: ${{ secrets.GH_PAT }}
#          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
#          MATCH_REPOSITORY: ${{ secrets.MATCH_REPOSITORY }}


#name: iOS One-Time Setup

#on: workflow_dispatch

#jobs:
#  setup:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: ruby/setup-ruby@v1
#        with:
#          ruby-version: 3.0
#          #bundler-cache: true

#      - run: bundle install
#      - name: Build iOS
#        shell: bash
#        run: |
#          bundle exec fastlane init_ci
#        env:
#          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
#          APP_STORE_CONNECT_KEY: ${{ secrets.APPSTORE_P8 }} # Raw .p8 value
#          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}

#          GH_PAT: ${{ secrets.GH_PAT }}
#          GITHUB_REPOSITORY: ${{ env.GITHU_REPOSITORY }}

#          MATCH_REPOSITORY: ${{ secrets.MATCH_REPOSITORY }}


##name: iOS One-Time Setup

##on: 
##  workflow_dispatch:

##jobs:
##  setup:
##    runs-on: ubuntu-latest
##    steps:
##    #- uses: actions/checkout@v2
##    - name: Ruby setup
##      uses: ruby/setup-ruby@v1
##      with:
##        ruby-version: 2.7
##        bundler-cache: true
##    - run: bundle install

##    - name: Build iOS
##      shell: bash
##      run: |
##        bundle exec fastlane init_ci
##      env:
##        APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
##        APP_STORE_CONNECT_KEY: ${{ secrets.APPSTORE_P8 }} # Raw .p8 value
##        APP_STORE_CONNECT_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}

##        GH_PAT: ${{ secrets.GH_PAT }}
##        GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
##        MATCH_REPOSITORY: ${{ secrets.MATCH_REPOSITORY }}